// a: Amar
// ac: aan cayinnayn
// baay: Baayoloji
// bot: Botani
// bul: Bulsho
// c.af: cilmig-afeed
// c.beer: cilmi beereed
// c.cimi: cilmiga cimilada
// c.fal: cilmi-falag
// c.naf: cilimi-nafsi
// c.nafl: cilmiga-naflayd
// ca: Cayiman
// daaw: Daawo
// dd: Diirad
// dh: Dheddig
// dhaq: Dhaqaale
// dhm: Dhimman
// dii: Diinta
// diid: Diidmo
// dk: Dibkabe
// e: Erey
// eb: Ebyoon
// e.d: erey dareen
// etno: Etnoloji
// f: Fal
// fals: Falsafad
// fiis: Fiisikis
// fk: Falkaab
// g: Gudbe
// h: Horyaale
// isrog: Isrogrog
// j: Jagaale
// jool: Jooloji
// juqr: Juqraafi
// ke: Keli
// kh: Khabar
// kiim: Kiimika
// l: Lab
// ld: la-mid
// lg: labagudbe
// lh: laahansho
// ly: layeele
// m: magac
// maan.: maanso
// mg: magudbe
// mi: mideeya
// mu: magacuyaal
// muus.: muusiko
// nax: naxwe
// q: qodob
// qaan: qaanuun
// qf: qof
// qr: qurub
// riw: riwaayad
// s: sifo
// sh.r: shanqar-raac
// siyaa.: siyaasad
// so: soocan
// t: tiraale
// taar.: taariikh
// tegno.: tegnology
// to.: tegnoloji
// ti: tilmaame
// tus: tusaale
// u: urur
// u-j: u jeediye
// w: wadar
// we: weyddimeed
// wr: weer
// xi: xiriiriye
// xis: xisaab
// y: yeele