class EngSomaliWord {
  final int position;
  final String word;
  final String meaning;

  EngSomaliWord(
    this.position, {
    required this.word,
    required this.meaning,
  });
}

List<EngSomaliWord> words = [
  EngSomaliWord(1, word: 'I', meaning: 'I'),
  EngSomaliWord(2, word: 'Do', meaning: 'Samee'),
  EngSomaliWord(3, word: 'Go', meaning: 'Tag'),
  EngSomaliWord(4, word: 'He', meaning: 'Isaga'),
  EngSomaliWord(5, word: 'Me', meaning: 'Aniga'),
  EngSomaliWord(6, word: 'My', meaning: 'Aniga'),
  EngSomaliWord(7, word: 'No', meaning: 'Maya'),
  EngSomaliWord(8, word: 'On', meaning: 'On'),
  EngSomaliWord(9, word: 'Or', meaning: 'Ama'),
  EngSomaliWord(10, word: 'So', meaning: 'Sidaas'),
  EngSomaliWord(11, word: 'Up', meaning: 'Kor'),
  EngSomaliWord(12, word: 'We', meaning: 'Anaga'),
  EngSomaliWord(13, word: 'Act', meaning: 'Fal'),
  EngSomaliWord(14, word: 'Add', meaning: 'Ku darso'),
  EngSomaliWord(15, word: 'Age', meaning: 'Dada'),
  EngSomaliWord(16, word: 'Aim', meaning: 'Ujeedo'),
  EngSomaliWord(17, word: 'Air', meaning: 'Hawo'),
  EngSomaliWord(18, word: 'All', meaning: 'Dhammaan'),
  EngSomaliWord(19, word: 'And', meaning: 'Iyo'),
  EngSomaliWord(20, word: 'Ant', meaning: 'Quraanjo'),
  EngSomaliWord(21, word: 'Any', meaning: 'Mid kasta'),
  EngSomaliWord(22, word: 'Ask', meaning: 'Weydii'),
  EngSomaliWord(23, word: 'Bad', meaning: 'Xun'),
  EngSomaliWord(24, word: 'Big', meaning: 'Weyn'),
  EngSomaliWord(25, word: 'Buy', meaning: 'Iibso'),
  EngSomaliWord(26, word: 'Cry', meaning: 'Ooyi'),
  EngSomaliWord(27, word: 'Dam', meaning: 'Biyo xidheen'),
  EngSomaliWord(28, word: 'Die', meaning: 'Dhiman'),
  EngSomaliWord(29, word: 'Dry', meaning: 'Qallalan'),
  EngSomaliWord(30, word: 'End', meaning: 'Dhamaad'),
  EngSomaliWord(31, word: 'Ear', meaning: 'Dhegta'),
  EngSomaliWord(32, word: 'Eat', meaning: 'Cun'),
  EngSomaliWord(33, word: 'Egg', meaning: 'Ukunta'),
  EngSomaliWord(34, word: 'Eye', meaning: 'Isha'),
  EngSomaliWord(35, word: 'Fat', meaning: 'Buuran'),
  EngSomaliWord(36, word: 'Fly', meaning: 'Duuli'),
  EngSomaliWord(37, word: 'Fun', meaning: 'Madadaalo'),
  EngSomaliWord(38, word: 'Get', meaning: 'Heli'),
  EngSomaliWord(39, word: 'God', meaning: 'Ilaah'),
  EngSomaliWord(40, word: 'Hen', meaning: 'Digaag'),
  EngSomaliWord(41, word: 'Hot', meaning: 'Kulul'),
  EngSomaliWord(42, word: 'Job', meaning: 'Shaqada'),
  EngSomaliWord(43, word: 'Leg', meaning: 'Lug'),
  EngSomaliWord(44, word: 'Lie', meaning: 'Been sheegid'),
  EngSomaliWord(45, word: 'Low', meaning: 'Hooseeya'),
  EngSomaliWord(46, word: 'Mad', meaning: 'Waalan'),
  EngSomaliWord(47, word: 'Man', meaning: 'Nin'),
  EngSomaliWord(48, word: 'Not', meaning: 'Maaha'),
  EngSomaliWord(49, word: 'Now', meaning: 'Hadda'),
  EngSomaliWord(50, word: 'New', meaning: 'Cusub'),
  EngSomaliWord(51, word: 'Old', meaning: 'Jir'),
  EngSomaliWord(52, word: 'Own', meaning: 'Leh'),
  EngSomaliWord(53, word: 'Run', meaning: 'Orod'),
  EngSomaliWord(54, word: 'Sad', meaning: 'Murugo'),
  EngSomaliWord(55, word: 'Sea', meaning: 'Badda'),
  EngSomaliWord(56, word: 'See', meaning: 'Eeg'),
  EngSomaliWord(57, word: 'Shy', meaning: 'Xishood'),
  EngSomaliWord(58, word: 'Sit', meaning: 'Fadhiiso'),
  EngSomaliWord(59, word: 'Sum', meaning: 'Wadar'),
  EngSomaliWord(60, word: 'Sun', meaning: 'Qorraxdu'),
  EngSomaliWord(61, word: 'Tax', meaning: 'Canshuur'),
  EngSomaliWord(62, word: 'Try', meaning: 'Isku day'),
  EngSomaliWord(63, word: 'Use', meaning: 'Isticmaal'),
  EngSomaliWord(64, word: 'War', meaning: 'Dagaal'),
  EngSomaliWord(65, word: 'Wet', meaning: 'Qoyan'),
  EngSomaliWord(66, word: 'Why', meaning: 'Sababta'),
  EngSomaliWord(67, word: 'Win', meaning: 'Guulayso'),
  EngSomaliWord(68, word: 'Yes', meaning: 'Haa'),
  EngSomaliWord(69, word: 'You', meaning: 'Adiga'),
  EngSomaliWord(70, word: 'Also', meaning: 'Sidoo kale'),
  EngSomaliWord(71, word: 'Baby', meaning: 'Dhallaan'),
  EngSomaliWord(72, word: 'Back', meaning: 'Dib u noqo'),
  EngSomaliWord(73, word: 'Bake', meaning: 'Dubay'),
  EngSomaliWord(74, word: 'Bald', meaning: 'Bidaar'),
  EngSomaliWord(75, word: 'Ball', meaning: 'Kubad'),
  EngSomaliWord(76, word: 'Bark', meaning: 'Jilif'),
  EngSomaliWord(77, word: 'Bath', meaning: 'Qubeyska'),
  EngSomaliWord(78, word: 'Beet', meaning: 'Dabocase'),
  EngSomaliWord(79, word: 'Bend', meaning: 'Foorarsi'),
  EngSomaliWord(80, word: 'Best', meaning: 'Ugu fiican'),
  EngSomaliWord(81, word: 'Bird', meaning: 'Shimbir'),
  EngSomaliWord(82, word: 'Bold', meaning: 'Geesinimo leh'),
  EngSomaliWord(83, word: 'Bone', meaning: 'Lafo'),
  EngSomaliWord(84, word: 'Book', meaning: 'Buug'),
  EngSomaliWord(85, word: 'Born', meaning: 'Dhashay'),
  EngSomaliWord(86, word: 'Both', meaning: 'Labadaba'),
  EngSomaliWord(87, word: 'Busy', meaning: 'Mashquul'),
  EngSomaliWord(88, word: 'Call', meaning: 'Wac'),
  EngSomaliWord(89, word: 'Calm', meaning: 'Degan'),
  EngSomaliWord(90, word: 'Care', meaning: 'Daryeel'),
  EngSomaliWord(91, word: 'Come', meaning: 'Kaalay'),
  EngSomaliWord(92, word: 'Cost', meaning: 'Kharashka'),
  EngSomaliWord(93, word: 'Cute', meaning: 'Qurux badan'),
  EngSomaliWord(94, word: 'Crow', meaning: 'Tuke'),
  EngSomaliWord(95, word: 'Dare', meaning: 'Dhiirran'),
  EngSomaliWord(96, word: 'Dark', meaning: 'Madow'),
  EngSomaliWord(97, word: 'Date', meaning: 'Taariikhda'),
  EngSomaliWord(98, word: 'Deal', meaning: 'Heshiis'),
  EngSomaliWord(99, word: 'Diet', meaning: 'Cunto'),
  EngSomaliWord(100, word: 'Dish', meaning: 'Saxan'),
  EngSomaliWord(76, word: 'Door', meaning: 'Albaabka'),
  EngSomaliWord(77, word: 'Down', meaning: 'Hoos'),
  EngSomaliWord(78, word: 'Dust', meaning: 'Siigada'),
  EngSomaliWord(79, word: 'Each', meaning: 'Mid walba'),
  EngSomaliWord(80, word: 'Earn', meaning: 'Kasban'),
  EngSomaliWord(81, word: 'Easy', meaning: 'Fudud'),
  EngSomaliWord(82, word: 'Edge', meaning: 'Gees'),
  EngSomaliWord(83, word: 'Evil', meaning: 'Xumaan'),
  EngSomaliWord(84, word: 'Exit', meaning: 'Ka bixid'),
  EngSomaliWord(85, word: 'Face', meaning: 'Waji'),
  EngSomaliWord(86, word: 'Fact', meaning: 'Xaqiiqda'),
  EngSomaliWord(87, word: 'Fair', meaning: 'Cadaalad ah'),
  EngSomaliWord(88, word: 'Fake', meaning: 'Been abuur ah'),
  EngSomaliWord(89, word: 'Farm', meaning: 'Beeralayda'),
  EngSomaliWord(90, word: 'Fast', meaning: 'Degdeg ah'),
  EngSomaliWord(91, word: 'Fear', meaning: 'Cabsi'),
  EngSomaliWord(92, word: 'Feel', meaning: 'Dareemo'),
  EngSomaliWord(93, word: 'Find', meaning: 'Heli'),
  EngSomaliWord(94, word: 'Fine', meaning: 'Ganaax'),
  EngSomaliWord(95, word: 'Fish', meaning: 'Kalluunka'),
  EngSomaliWord(96, word: 'Food', meaning: 'Cunto'),
  EngSomaliWord(97, word: 'Fool', meaning: 'Doqon'),
  EngSomaliWord(98, word: 'Free', meaning: 'Bilaasha'),
  EngSomaliWord(99, word: 'Frog', meaning: 'Rah'),
  EngSomaliWord(100, word: 'Full', meaning: 'Buuxa'),
  EngSomaliWord(101, word: 'Door', meaning: 'albaabka'),
  EngSomaliWord(102, word: 'Down', meaning: 'hoos'),
  EngSomaliWord(103, word: 'Dust', meaning: 'siigada'),
  EngSomaliWord(104, word: 'Each', meaning: 'mid walba'),
  EngSomaliWord(105, word: 'Earn', meaning: 'kasban'),
  EngSomaliWord(106, word: 'Easy', meaning: 'fudud'),
  EngSomaliWord(107, word: 'Edge', meaning: 'gees'),
  EngSomaliWord(108, word: 'Evil', meaning: 'xumaan'),
  EngSomaliWord(109, word: 'Exit', meaning: 'ka bixid'),
  EngSomaliWord(110, word: 'Face', meaning: 'waji'),
  EngSomaliWord(111, word: 'Fact', meaning: 'xaqiiqda'),
  EngSomaliWord(112, word: 'Fair', meaning: 'cadaalad ah'),
  EngSomaliWord(113, word: 'Fake', meaning: 'been abuur ah'),
  EngSomaliWord(114, word: 'Farm', meaning: 'beeralayda'),
  EngSomaliWord(115, word: 'Fast', meaning: 'degdeg ah'),
  EngSomaliWord(116, word: 'Fear', meaning: 'cabsi'),
  EngSomaliWord(117, word: 'Feel', meaning: 'dareemo'),
  EngSomaliWord(118, word: 'Find', meaning: 'heli'),
  EngSomaliWord(119, word: 'Fine', meaning: 'ganaax'),
  EngSomaliWord(120, word: 'Fish', meaning: 'kalluunka'),
  EngSomaliWord(121, word: 'Food', meaning: 'cunto'),
  EngSomaliWord(122, word: 'Fool', meaning: 'doqon'),
  EngSomaliWord(123, word: 'Free', meaning: 'bilaasha'),
  EngSomaliWord(124, word: 'Frog', meaning: 'rah'),
  EngSomaliWord(125, word: 'Full', meaning: 'buuxa'),
  EngSomaliWord(126, word: 'Gape', meaning: 'farqiga'),
  EngSomaliWord(127, word: 'Gift', meaning: 'hadyad'),
  EngSomaliWord(128, word: 'Girl', meaning: 'gabadh'),
  EngSomaliWord(129, word: 'Goat', meaning: 'ari'),
  EngSomaliWord(130, word: 'Good', meaning: 'wanaagsan'),
  EngSomaliWord(131, word: 'Grab', meaning: 'qabsato'),
  EngSomaliWord(132, word: 'Grow', meaning: 'koraan'),
  EngSomaliWord(133, word: 'Half', meaning: 'kala badh'),
  EngSomaliWord(134, word: 'Hate', meaning: 'nacayb'),
  EngSomaliWord(135, word: 'Head', meaning: 'madax'),
  EngSomaliWord(136, word: 'Hear', meaning: 'maqal'),
  EngSomaliWord(137, word: 'Heat', meaning: 'kulaylka'),
  EngSomaliWord(138, word: 'Help', meaning: 'I caawi'),
  EngSomaliWord(139, word: 'Here', meaning: 'halkan'),
  EngSomaliWord(140, word: 'Hide', meaning: 'qari'),
  EngSomaliWord(141, word: 'High', meaning: 'sare'),
  EngSomaliWord(142, word: 'Hold', meaning: 'hayn'),
  EngSomaliWord(143, word: 'Hole', meaning: 'dalool'),
  EngSomaliWord(144, word: 'Home', meaning: 'guriga'),
  EngSomaliWord(145, word: 'Huge', meaning: 'weyn'),
  EngSomaliWord(146, word: 'Hurt', meaning: 'dhaawacday'),
  EngSomaliWord(147, word: 'Idea', meaning: 'fikrad'),
  EngSomaliWord(148, word: 'Jump', meaning: 'bood'),
  EngSomaliWord(149, word: 'Just', meaning: 'kaliya'),
  EngSomaliWord(150, word: 'Kill', meaning: 'dil'),
  EngSomaliWord(151, word: 'Land', meaning: 'dhulka'),
  EngSomaliWord(152, word: 'Last', meaning: 'u dambeeya'),
  EngSomaliWord(153, word: 'Late', meaning: 'daahsan'),
  EngSomaliWord(154, word: 'Left', meaning: 'bidix'),
  EngSomaliWord(155, word: 'Life', meaning: 'nolosha'),
  EngSomaliWord(156, word: 'Line', meaning: 'line'),
  EngSomaliWord(157, word: 'Lion', meaning: 'libaax'),
  EngSomaliWord(158, word: 'Long', meaning: 'dheer'),
  EngSomaliWord(159, word: 'Look', meaning: 'fiiri'),
  EngSomaliWord(160, word: 'Lost', meaning: 'luntay'),
  EngSomaliWord(161, word: 'Love', meaning: 'jacayl'),
  EngSomaliWord(162, word: 'Luck', meaning: 'nasiib'),
  EngSomaliWord(163, word: 'Lung', meaning: 'sambabada'),
  EngSomaliWord(164, word: 'Many', meaning: 'badan'),
  EngSomaliWord(165, word: 'Meet', meaning: 'kulmi'),
  EngSomaliWord(166, word: 'Melt', meaning: 'dhalaali'),
  EngSomaliWord(167, word: 'Milk', meaning: 'caano'),
  EngSomaliWord(168, word: 'Must', meaning: 'waa in'),
  EngSomaliWord(169, word: 'Name', meaning: 'magac'),
  EngSomaliWord(170, word: 'Near', meaning: 'dhow'),
  EngSomaliWord(171, word: 'Neat', meaning: 'nadiif ah'),
  EngSomaliWord(172, word: 'Neck', meaning: 'luqunta'),
  EngSomaliWord(173, word: 'Need', meaning: 'baahan'),
  EngSomaliWord(174, word: 'Next', meaning: 'soo socda'),
  EngSomaliWord(175, word: 'Only', meaning: 'kaliya'),
  EngSomaliWord(176, word: 'Pain', meaning: 'xanuun'),
  EngSomaliWord(177, word: 'Pair', meaning: 'lammaane'),
  EngSomaliWord(178, word: 'Park', meaning: 'baarkinka'),
  EngSomaliWord(179, word: 'Path', meaning: 'waddo'),
  EngSomaliWord(180, word: 'Play', meaning: 'ciyaar'),
  EngSomaliWord(181, word: 'Poor', meaning: 'miskiin'),
  EngSomaliWord(182, word: 'Pull', meaning: 'jiidid'),
  EngSomaliWord(183, word: 'Pure', meaning: 'saafi ah'),
  EngSomaliWord(184, word: 'Quit', meaning: 'joojin'),
  EngSomaliWord(185, word: 'Quiz', meaning: 'suaalo'),
  EngSomaliWord(186, word: 'Race', meaning: 'jinsiyad'),
  EngSomaliWord(187, word: 'Rain', meaning: 'roobka'),
  EngSomaliWord(188, word: 'Rare', meaning: 'naadir'),
  EngSomaliWord(189, word: 'Real', meaning: 'dhab ah'),
  EngSomaliWord(190, word: 'Rent', meaning: 'kirada'),
  EngSomaliWord(191, word: 'Rest', meaning: 'naso'),
  EngSomaliWord(192, word: 'Rich', meaning: 'hodan'),
  EngSomaliWord(193, word: 'Ride', meaning: 'fuulid'),
  EngSomaliWord(194, word: 'Rise', meaning: 'kac'),
  EngSomaliWord(195, word: 'Risk', meaning: 'khatarta'),
  EngSomaliWord(196, word: 'Room', meaning: 'Qol'),
  EngSomaliWord(197, word: 'Rope', meaning: 'xadhig'),
  EngSomaliWord(198, word: 'Rude', meaning: 'edeb daran'),
  EngSomaliWord(199, word: 'Sage', meaning: 'xikmad'),
  EngSomaliWord(200, word: 'Sail', meaning: 'shiraac'),
  EngSomaliWord(201, word: 'Salt', meaning: 'cusbo'),
  EngSomaliWord(202, word: 'Same', meaning: 'isku mid ah'),
  EngSomaliWord(203, word: 'Sand', meaning: 'ciid'),
  EngSomaliWord(204, word: 'Save', meaning: 'badbaadi'),
  EngSomaliWord(205, word: 'Scam', meaning: 'fadeexad'),
  EngSomaliWord(206, word: 'Seed', meaning: 'abuur'),
  EngSomaliWord(207, word: 'Seek', meaning: 'raadi'),
  EngSomaliWord(208, word: 'Self', meaning: 'nafta'),
  EngSomaliWord(209, word: 'Sell', meaning: 'iibiso'),
  EngSomaliWord(210, word: 'Send', meaning: 'dir'),
  EngSomaliWord(211, word: 'Shop', meaning: 'dukaan'),
  EngSomaliWord(212, word: 'Show', meaning: 'show'),
  EngSomaliWord(213, word: 'Sick', meaning: 'buka'),
  EngSomaliWord(214, word: 'Side', meaning: 'dhinac'),
  EngSomaliWord(215, word: 'Site', meaning: 'goobta'),
  EngSomaliWord(216, word: 'Size', meaning: 'cabbirka'),
  EngSomaliWord(217, word: 'Skin', meaning: 'maqaarka'),
  EngSomaliWord(218, word: 'Slow', meaning: 'gaabis ah'),
  EngSomaliWord(219, word: 'Soft', meaning: 'jilicsan'),
  EngSomaliWord(220, word: 'Soil', meaning: 'ciidda'),
  EngSomaliWord(221, word: 'Some', meaning: 'qaar'),
  EngSomaliWord(222, word: 'Soon', meaning: 'dhawaan'),
  EngSomaliWord(223, word: 'Stay', meaning: 'joog'),
  EngSomaliWord(224, word: 'Stop', meaning: 'joojin'),
  EngSomaliWord(225, word: 'Such', meaning: 'sida'),
  EngSomaliWord(226, word: 'Swap', meaning: 'is dhaafsi'),
  EngSomaliWord(227, word: 'Swim', meaning: 'dabaal'),
  EngSomaliWord(228, word: 'Take', meaning: 'qaado'),
  EngSomaliWord(229, word: 'Talk', meaning: 'hadal'),
  EngSomaliWord(230, word: 'Tall', meaning: 'dheer'),
  EngSomaliWord(231, word: 'Team', meaning: 'kooxda'),
  EngSomaliWord(232, word: 'Tell', meaning: 'sheeg'),
  EngSomaliWord(233, word: 'Tent', meaning: 'teendho'),
  EngSomaliWord(234, word: 'That', meaning: 'in'),
];
